version: "3.9"

services:
  app:
    container_name: ${PROJECT_NAME}_app
    volumes:
      - ./app:/app
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - ${APP_HOST_PORT}:8080
