"""create todo

Revision ID: 5b421748f9b9
Revises: 8f1b6fe8e874
Create Date: 2023-05-09 09:29:55.250991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b421748f9b9'
down_revision = '8f1b6fe8e874'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False, comment='タイトル'),
    sa.Column('content', sa.String(length=300), nullable=False, comment='内容'),
    sa.Column('done', sa.Boolean(), nullable=True, comment='完了したかどうか'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp'), nullable=False, comment='作成日時'),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp on update current_timestamp'), nullable=False, comment='更新日時'),
    sa.PrimaryKeyConstraint('id'),
    comment='TODOテーブル'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos')
    # ### end Alembic commands ###
